### ISSUE TITLE
Use seeded randomness

### ISSUE THREAD

**Issue by mortendahl** [mortendahl/tf-encrypted#137] opened 2018-09-19 13:08 UTC
Reduce networking by sending seeds instead of expanded tensors when possible.

WIP: https://github.com/mortendahl/tf-encrypted/tree/seeds
Issue posted to tf: https://github.com/tensorflow/tensorflow/issues/21974

**Comment by mortendahl** [comment] 2018-09-19 13:09
blocked waiting for either feedback from tensorflow team or getting custom ops running

**Comment by justin1121** [comment] 2018-09-25 20:31
Hey @mortendahl. I discovered this set of random functions that take seeds as tensors. https://www.tensorflow.org/api_docs/python/tf/contrib/stateless/stateless_random_uniform

**Comment by justin1121** [comment] 2018-09-26 14:35
Investigated this a little bit and I'm not quite it will be useful because it can't return ints only floats. We would have to scale the floats to the maximum range and according to @mortendahl this will not provide an even distribution over all the available ints.

One way forward would be to look at the ops for returning random ints and this new stateless random op and borrow some code from each to make our own custom op that does exactly what we need.

Random Uniform Int Op: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/random_op.cc#L217

You can see how it creates a distribution for low to high here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/random_op.cc#L250

StateLess Random Base Op: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/stateless_random_ops.cc#L67

Implementation of Fill for the base Op: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/stateless_random_ops.cc#L105

And you can see here the `Distribution` not being created a low or high value: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/stateless_random_ops.cc#L110

**Comment by mortendahl** [comment] 2018-09-27 07:36
think this is exactly the approach we should take (using a CPRG)

**Comment by ianlivingstone** [comment] 2018-10-22 18:56
Assigning @justin1121 and moving out of blocked.

We want to spend some time researching custom ops and how we'd package them into our distribution (the artifact we push up to pypi) and how it'd affect the installation experience for our users. Most importantly, how would this impact our own build pipeline? Would we need to do something extra to build and package up the custom op?

Furthermore, what's block our ability to implement a custom op for random seeds today? Anything? Are there other speed ups or use cases for custom ops that'd enable us to realize performance improvements?

Once we have a good understanding of the above questions we can start implementation!

**Comment by ianlivingstone** [comment] 2018-10-23 15:41
@justin1121 the library I was talking about: https://github.com/jedisct1/libsodium

**Comment by mortendahl** [comment] 2018-10-23 15:57
agree, and believe it's easy to install with pip etc.

these are probably the functions to look at: https://download.libsodium.org/doc/generating_random_data

**Comment by justin1121** [comment] 2018-10-23 19:59
Including custom ops in our distribution shouldn't affect the user's installation experience. All of the burden will be handled by our build workflow. The biggest change to our workflow is that we'll need to build a wheel for each platform we plan on supporting. When building a custom op we will need to build a shared object file that will not be portable between platforms. The toughest part of this is just spinning up the correct machines for each platform we want to support and getting the fiddly bits of the Makefile correct.

Including custom ops that rely on third party libraries (e.g. libsodium) is a separate challenge. I'm not sure how we'd accomplish this right now. My best idea so far is that we'd have to distribute a libsodium shared object which doesn't seem ideal to me but maybe its fine. Another solution is to statically link the third party library into the custom op shared object. 

Specifically, for libsodium, I was hoping that the python wrappers for libsodium (https://github.com/pyca/pynacl) would handle installing the libsodium libraries into the correct places depending on the platform. If that was the case then we'd be able to just install that as a dependency and get libsodium installed for free. As far as I can tell though pynacl is building a shared object (using ffi) that statically links in the libsodium library. Perhaps that is a hint that that is what we should be doing something similar. Would love to hear @mortendahl or @ianlivingstone thoughts on this.

As for implementing the seeded randomness, we no longer have anything directly blocking us. We've decided to use libsodium and there seems to be a straightforward path to including a naive implementation of a CSPRNG function as a custom op. We can use some of tensorflow's random number generating code as a guide to help us code this correctly. The harder part to this is making sure we parallelize everything correctly. Tensorflow is doing this for their random number generators so its a good place to start looking but we'll need to make sure we test everything throughly.

**Comment by ianlivingstone** [comment] 2018-10-24 12:40
> The toughest part of this is just spinning up the correct machines for each platform we want to support and getting the fiddly bits of the Makefile correct.

Does Circle CI provide the functionality we need to pull this off? It sounds like we'd at minimum need to introduce a build for each platform that then shipped an artifact for use in the "deploy/packaging" flow.

> Including custom ops that rely on third party libraries (e.g. libsodium) is a separate challenge. I'm not sure how we'd accomplish this right now. My best idea so far is that we'd have to distribute a libsodium shared object which doesn't seem ideal to me but maybe its fine. Another solution is to statically link the third party library into the custom op shared object.

One thought I have is that we could bundle up the custom operations as separate libraries (e.g. `tensorflow-secure-random` or similar) where all of the complexity of building the shared objects for each platform is maintained (including the complicated platform specific build pipeline). Then in this project, we'd just include the library as a dependency in our `setup.py` and `requirements.txt`.

**Comment by justin1121** [comment] 2018-10-24 16:59
> Distributing a single shared object is far easier than two :) So, ideally, we build a single shared object that has all of our dependencies statically linked if possible.

Confirmed that this is what PyNaCL is doing so yeah this is probably the best way. We can borrow some of the stuff they've already figured out to build the libsodium package as a static library.

> Does Circle CI provide the functionality we need to pull this off? It sounds like we'd at minimum need to introduce a build for each platform that then shipped an artifact for use in the "deploy/packaging" flow.

I think we'd want a separate "deploy/packaging" flow for each platform because whatever package comes out of that is platform specific. I assume we'll have to create separate deploy flows in the circleci `config.yml` file and select the correct docker image. It looks like for macos we wouldn't be able to build using a docker image we would have to do something like here https://circleci.com/docs/2.0/testing-ios/. Not sure if this matters or not..

**Comment by justin1121** [comment] 2018-10-25 13:40
> If we consumed the custom op as a package inside this repository would we still need the separate build workflows?

We wouldn't need separate workflows for tf-encrypted but we'd need them for the custom package.

I'm on the fence whether it would be better to have the custom op in a separate repository or just included in tf-encrypted. While it would be nice to hide the complexity of building the shared libraries I'm not sure it really matters that much. There would also be added complexity with managing another repository. One other thing that weirds me out is shipping a separate package that only contains a shared object and no python code. While this is doable by including a dummy package with an empty `__init__.py`, its not really ideal. I know @mortendahl had opinions related to this so it'd be great to hear his feedback before moving forward with any of this.

**Comment by ianlivingstone** [comment] 2018-10-25 14:06
> One other thing that weirds me out is shipping a separate package that only contains a shared object and no python code

I was thinking the code for the op would live in the repository as well so it'd be re-usable by any other project that wanted a secure random source in tensorflow.

> I'm on the fence whether it would be better to have the custom op in a separate repository or just included in tf-encrypted. 

We can start here and then split out later as well, that'd be a fine approach. Generally thinking it would be a more isolated change if it was kept to another package and easier to iterate on without breaking things here. Might be overkill though for this stage.

**Comment by justin1121** [comment] 2018-10-25 14:18
> I was thinking the code for the op would live in the repository as well so it'd be re-usable by any other project that wanted a secure random source in tensorflow.

As far as I can tell the custom op would be totally written in C++ so there would be no python code to ship, is what I mean. We might want to wrap it in python code at some point though as that's how all the rest of the ops in tensorflow are used not sure if its necessary to begin with though. This doesn't really matter if we're just leaving the code in tf-encrypted.

> We can start here and then split out later as well, that'd be a fine approach. 

I think this is what I'm most comfortable at this point. It'll be easier to split this code out in the future than to bring it back into tf-encrypted if we end up making the wrong decision. 😄

**Comment by justin1121** [comment] 2018-10-25 15:45
> Don't know if that means one build or several.

I think that's up to how we want to do it. We could have a separate shared object for each custom op or one shared object for all the custom ops we create.

> Re parallel, that definitely makes sense; generation randomness for sub-tensors and then merging them afterwards would be one way of doing that.

Found some example code of doing this sort of thing in parallel here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/random_op.cc#L78

Basically `FillPhiloxRandomTask::Run()` gets called a bunch of times by different threads which gets passed thread information to fill in the correct indices that the individual threads are told to manage. I assume this would be secure but maybe not!

**Comment by ianlivingstone** [comment] 2018-10-25 16:00
> I think that's up to how we want to do it. We could have a separate shared object for each custom op or one shared object for all the custom ops we create.

Separate for each would be cleaner but there might be bloat inside the built artifact as a result (e.g. if each includes the same libraries that'd be duplicated). 

I'd say lets start with this and figure it out when we move onto the next custom op.

**Comment by mortendahl** [comment] 2018-10-25 16:10
Sounds good. Do you have enough @justin1121 to look further into this?

**Comment by mortendahl** [comment] 2018-10-29 08:48
Some additional suggestions here: https://github.com/tensorflow/tensorflow/issues/21974#issuecomment-433286598. They seem more involved than using a custom op though.

**Comment by justin1121** [comment] 2018-10-29 12:59
Yeah saw that. Believe we've already discounted the stateless ops. Haven't looked into the other suggestion much yet.

**Comment by justin1121** [comment] 2018-11-02 18:45
Secure random custom op has almost landed so we'll need to consider how we implement seeded randomness along with the work we plan on doing for the tensor api refactor.

**Closed** 2018-12-03 21:58 UTC
Labels: ready-for-review
