### ISSUE TITLE
Implement SecureNN protocol

### ISSUE THREAD

**Issue by mortendahl** [mortendahl/tf-encrypted#2] opened 2018-06-05 11:42 UTC
The 3/4-party [SecureNN](https://eprint.iacr.org/2018/442) protocol claims good performance as well as offering additional activation functions such as ReLU without switching GC (using existing protocols that seems adaptable to the 2-party setting as well).

**Comment by snwagh** [comment] 2018-08-10 07:25
@mortendahl, @koenvanderveen I intend to open source the code soon.

**Comment by mortendahl** [comment] 2018-08-11 19:59
that's great @snwagh! which language/platform did you use? interested in helping porting it to TensorFlow?

**Comment by snwagh** [comment] 2018-08-14 12:53
The entire code is in C++. 
Porting to TensorFlow sounds fun, though I might have too many commitments for a while. Keep me in the loop and I'll try to contribute however I can.

**Comment by mortendahl** [comment] 2018-08-23 21:02
any updates on getting the source code out @snwagh?

**Comment by snwagh** [comment] 2018-08-25 04:33
Hi @mortendahl, not yet, I was thinking more of three/four weeks time.

**Comment by bendecoste** [comment] 2018-09-06 14:55
I think we are ready to go ahead and implement this.  There was some prototyping done by @jvmancuso and myself.  We should be able to OS that code pretty soon but the gist is that we have the protocol implemented in python with numpy.

The plan is to continue developing in secureNN.py as it is setup now, since secureNN is a superset of spdz this seems like a pretty natural decision.  We used numpy and all of the functions are vectorized so the translation to TF should be fairly straight forward with a couple caveats:

- We may need new tensor types
The rings used in secureNN do not directly translate to what we are doing via CRT, we will likely need to come up with new mods for each share of the CRT (cc @mortendahl)
  - We need new types for Z_2^64 as well as Z_2^64-1
- Figure out the smallest tensor type we can use for Z_p (probably int16 because values can temporarily go negative during some ops, so unsigned int8 wouldn't fit them)

It is possible that these caveats would just go away if we have int64 tensors.  There was some work done in the TF repo that discovered this may be an artificial boundary that we can just turn off.

**Comment by mortendahl** [comment] 2018-09-17 09:53
hi @snwagh, just a ping in case you're interested in following along: work on this is now happening in the [securenn](https://github.com/mortendahl/tf-encrypted/tree/securenn) branch, primarily as a new protocol [`SecureNN`](https://github.com/mortendahl/tf-encrypted/blob/securenn/tensorflow_encrypted/protocol/securenn.py) deriving from [`Pond`](https://github.com/mortendahl/tf-encrypted/blob/securenn/tensorflow_encrypted/protocol/pond.py)

**Comment by ianlivingstone** [comment] 2018-09-17 12:50
This is a duplicate of #106, we should consider closing this up!

**Closed** 2018-09-17 15:06 UTC
Labels: discovery
